###
### Retrieve a token that can be used for calls requiring authentication
###
POST {{protocol}}{{host}}:{{port}}/users/tokens
Content-Type: application/json
Accept: application/json

{
  "username": "harun",
  "password": "gokcegoz"
}

> {%
client.global.set("token", response.body.accessToken);
%}

